# Generated by Django 6.0.2 on 2026-02-15 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_committee_alter_participant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 2, 15)),
        ),
    ]
