# Generated by Django 6.0.2 on 2026-02-17 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 2, 17)),
        ),
        migrations.AlterField(
            model_name='report',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='reports.participant'),
        ),
    ]
