# Generated by Django 6.0.2 on 2026-02-18 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_date_of_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 2, 18)),
        ),
    ]
