# Generated by Django 6.0.2 on 2026-02-27 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 2, 27)),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
