# Generated by Django 6.0.2 on 2026-02-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_category_options_alter_report_date_of_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='committee',
        ),
        migrations.AddField(
            model_name='report',
            name='committees',
            field=models.ManyToManyField(blank=True, to='reports.committee'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
    ]
