# Generated by Django 6.0.2 on 2026-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_date_of_report_alter_report_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='committee',
        ),
        migrations.AddField(
            model_name='report',
            name='committees',
            field=models.ManyToManyField(blank=True, null=True, to='reports.committee'),
        ),
    ]
