# Generated by Django 6.0.2 on 2026-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_committee_report_committees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
