# Generated by Django 6.0.2 on 2026-03-02 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_committee_report_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 3, 2)),
        ),
    ]
