# Generated by Django 6.0.2 on 2026-03-17 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 3, 17)),
        ),
    ]
