# Generated by Django 6.0.2 on 2026-03-18 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_state_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 3, 18)),
        ),
    ]
