# Generated by Django 6.0.2 on 2026-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_staffprofile_gender_staffprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
