# Generated by Django 6.0.2 on 2026-03-20 20:48

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_report_date_of_report_alter_report_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='report',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
