# Generated by Django 6.0.2 on 2026-04-05 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_report_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='state',
        ),
        migrations.AddField(
            model_name='report',
            name='isActive',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.date(2026, 4, 5)),
        ),
    ]
