# Generated by Django 6.0.2 on 2026-04-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_report_state_report_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='committees',
            field=models.ManyToManyField(blank=True, to='reports.committee'),
        ),
    ]
