# Generated by Django 6.0.2 on 2026-04-05 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_report_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.datetime(2026, 4, 5, 4, 22, 49, 377240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='participants',
            field=models.ManyToManyField(blank=True, to='reports.participant'),
        ),
    ]
