# Generated by Django 6.0.2 on 2026-04-05 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_report_date_of_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.datetime(2026, 4, 5, 4, 34, 18, 501292, tzinfo=datetime.timezone.utc)),
        ),
    ]
