# Generated by Django 6.0.2 on 2026-04-05 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='report',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=datetime.datetime(2026, 4, 5, 15, 20, 37, 949143, tzinfo=datetime.timezone.utc)),
        ),
    ]
