# Generated by Django 6.0.2 on 2026-04-06 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_report_managers_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
