# Generated by Django 6.0.2 on 2026-04-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_alter_report_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='feature_image',
            field=models.ImageField(default='https://res.cloudinary.com/dop5fzjom/image/upload/v1775723804/images/report_images/uwi_zocrhc.jpg', upload_to='report_images'),
        ),
    ]
