# Generated by Django 6.0.2 on 2026-04-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_fix_image_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
