# Generated by Django 6.0.2 on 2026-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofilepic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilepic',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofilepic',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
