# Generated by Django 6.0.2 on 2026-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_image_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profilePic',
            field=models.ImageField(default='https://res.cloudinary.com/dop5fzjom/image/upload/v1775723467/images/profile_pictures/user_qift6z.png', max_length=500, upload_to='profile_pictures'),
        ),
    ]
